# bit string(s) to search for in the database
SEARCH_TARGETS = [
    "1010111"[::-1],
]

# number of shots to approximate the result of the program
SHOT_COUNT = 10000

# whether to apply optimisation to our generated QASM
# performance improvement of ~20-50%
OPTIMISE = True

# replace toffoli gates with 1 and 2 qubit gate counterparts
# uses the same number of ancillary bits, ~30% slower
USE_ALT_TOFFOLI = True

# use a custom n-bit CROT instead of the toffoli-built CNOT
# this uses 0 ancillary bits, and avoids any toffoli gates
# approximately 10x slower than using toffoli gates directly (in simulator)
# NB: This setting overrides USE_ALT_TOFFOLI
USE_CROT = True


# autogenerated parameters
SEARCH_TARGET_HEXES = list(map(lambda s: hex(int(s[::-1], 2))[2:],
                               SEARCH_TARGETS))

DATA_QUBITS = len(SEARCH_TARGETS[0])

if USE_CROT:
    ANCILLARY_QUBITS = 0
else:
    ANCILLARY_QUBITS = DATA_QUBITS - 3

QUBIT_COUNT = DATA_QUBITS + ANCILLARY_QUBITS
